# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class SpiderItem(scrapy.Item):
#    image              = scrapy.Field()
#    is_replyable       = scrapy.Field()
#    channels           = scrapy.Field()
#    channel_keys       = scrapy.Field()
#    preface            = scrapy.Field()
#    id                 = scrapy.Field()
#    subject            = scrapy.Field()
#    copyright          = scrapy.Field()
#    author             = scrapy.Field()
#    image_description  = scrapy.Field()
#    is_show_summary    = scrapy.Field()
#    minisite_key       = scrapy.Field()
#    image_info         = scrapy.Field()
#    subject_key        = scrapy.Field()
#    minisite           = scrapy.Field()
#    tags               = scrapy.Field()
#    date_published     = scrapy.Field()
#    authors            = scrapy.Field()
#    replies_count      = scrapy.Field()
#    is_author_external = scrapy.Field()
#    recommends_count   = scrapy.Field()
#    title_hide         = scrapy.Field()
#    date_modified      = scrapy.Field()
#    url                = scrapy.Field()
#    title              = scrapy.Field()
#    small_image        = scrapy.Field()
#    summary            = scrapy.Field()
#    ukey_author        = scrapy.Field()
#    date_created       = scrapy.Field()
#    resource_url       = scrapy.Field()
#    article            = scrapy.Field()
    image = scrapy.Field()
    is_replyable = scrapy.Field()
    channels = scrapy.Field()
    channel_keys = scrapy.Field()
    preface = scrapy.Field()
    id = scrapy.Field()
    subject = scrapy.Field()
    copyright = scrapy.Field()
    author = scrapy.Field()
    image_description = scrapy.Field()
    content = scrapy.Field()
    is_show_summary = scrapy.Field()
    minisite_key = scrapy.Field()
    image_info = scrapy.Field()
    subject_key = scrapy.Field()
    minisite = scrapy.Field()
    tags = scrapy.Field()
    date_published = scrapy.Field()
    authors = scrapy.Field()
    replies_count = scrapy.Field()
    is_author_external = scrapy.Field()
    recommends_count = scrapy.Field()
    title_hide = scrapy.Field()
    date_modified = scrapy.Field()
    url = scrapy.Field()
    title = scrapy.Field()
    small_image = scrapy.Field()
    summary = scrapy.Field()
    ukey_author = scrapy.Field()
    date_created = scrapy.Field()
    resource_url = scrapy.Field()
